### ISSUE TITLE
Incomplete models for the database.

### ISSUE THREAD

**Issue by Varun487** [acmpesuecc/Todo_List_In_Django#8]
Complete the model 'Todo' in models.py with the attributes given in the README.md namely
1. create a title attribute -> character field (add a reasonable max length)
2. create a content attribute -> text
3. create a created_at attribute -> timestamp (use imported datetime module)
4. create priority attribute -> integer
5. create priority attribute -> integer
6. In the __str__ function, return the todo object's title

**Comment by anirudhRowjee** [comment]
hi, can I do this?

**Comment by Varun487** [comment]
Hey @anirudhRowjee , Are you part of HackNight by PES University? If yes please ping me on the discord server.
